# Generated by Django 3.0 on 2020-06-10 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('Next_of_kin', models.CharField(blank=True, max_length=255, null=True)),
                ('card', models.CharField(blank=True, max_length=255, null=True)),
                ('date_admitted', models.DateTimeField(auto_now_add=True)),
                ('possible_diagnosis', models.TextField(max_length=255)),
                ('symptoms', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AssignPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('ward', models.CharField(max_length=255)),
                ('Discharge', models.IntegerField(default=0)),
                ('Death', models.IntegerField(default=0)),
                ('date_Release', models.DateTimeField(auto_now_add=True)),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurse', to='Data.Nurse')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='Data.Patient')),
            ],
        ),
    ]
