# Generated by Django 3.0 on 2020-06-10 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignpatient',
            old_name='date_Release',
            new_name='date_discharged',
        ),
    ]
